### ISSUE TITLE
the WAST-02 Report bugs to Microsoft section is outdated

### ISSUE THREAD

**Issue by m8ram** [PoshCode/PowerShellPracticeAndStyle#75]
The section [WAST-02 Report bugs to Microsoft](https://github.com/PoshCode/PowerShellPracticeAndStyle/blob/master/Best%20Practices/Building%20Reusable%20Tools.md#wast-02-report-bugs-to-microsoft) instructs users to report bugs to Connect.Microsoft.com. However the Powershell page on Connect redirects users to [Powershell UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell) based on [this blog post](http://blogs.msdn.com/b/powershell/archive/2015/12/14/improving-the-powershell-feedback-experience-with-uservoice.aspx).

And to complicate matters more that blog post contains a recommendation to submit feedback for our [open-source projects](https://github.com/powershell) via GitHub Issues.

Please update the guide with the correct or at least recommended location to report issues.
And if more than one issue tracker is being actively used please explain when to use one or the other.

**Comment by Jaykul** [comment]
Fixed this finally ;-)

**Comment by m8ram** [comment]
@Jaykul : how is this fixed exactly?
- The WAST-02 Report bugs to Microsoft page no longer exists: I get an error 404 page not found.
- Connect.microsoft.com says "Microsoft Connect Has Been Retired"
- the blog post I linked to now reports error 403 forbidden

The only page that still exists nearly 4 years after I reported this is the [Powershell UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell) page that now says "The PowerShell forum accepts bug reports as well as feedback and suggestions." Is UserVoice the place to log issues with PowerShell now?

Or can we open issues in this project as [The PowerShell Best Practices and Style Guide](https://github.com/PoshCode/PowerShellPracticeAndStyle) seems to suggest?

**Comment by Jaykul** [comment]
The content is there just like always. That old link is broken, but only because we removed spaces from file names. See [Building Reusable Tools](https://github.com/PoshCode/PowerShellPracticeAndStyle/blob/master/Best-Practices/Building-Reusable-Tools.md#wast-02-report-bugs-to-microsoft).

I updated the content, so it says to [report the bug on github.com/PowerShell](https://github.com/PowerShell/PowerShell/issues)...
